import { Router, Request, Response } from 'express';
import { query } from '../db/pool';
import { authMiddleware } from '../middleware/auth';
import { AppConfig } from '../types';

const router = Router();

function generateReactComponent(config: AppConfig): string {
  const pages = config.ui?.pages || [];
  return `// Auto-generated by AppForge
import React from 'react';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';

${pages.map(page => `
function ${page.name.replace(/\s+/g, '')}Page() {
  return (
    <div className="page">
      <h1>${page.title || page.name}</h1>
      ${page.components?.map(comp => `
      <div className="component ${comp.type}">
        <h2>${comp.title || ''}</h2>
        {/* ${comp.type} component */}
      </div>`).join('\n') || ''}
    </div>
  );
}
`).join('\n')}

export default function App() {
  return (
    <BrowserRouter>
      <nav>
        ${pages.map(p => `<Link to="${p.path}">${p.name}</Link>`).join('\n        ')}
      </nav>
      <Routes>
        ${pages.map(p => `<Route path="${p.path}" element={<${p.name.replace(/\s+/g, '')}Page />} />`).join('\n        ')}
      </Routes>
    </BrowserRouter>
  );
}
`;
}

function generateExpressRoutes(config: AppConfig): string {
  const endpoints = config.api?.endpoints || [];
  return `// Auto-generated by AppForge
const express = require('express');
const router = express.Router();

${endpoints.map(ep => `
// ${ep.name}
router.${ep.method.toLowerCase()}('${ep.path}', async (req, res) => {
  try {
    // TODO: Implement ${ep.name}
    res.json({ success: true, data: [] });
  } catch (err) {
    res.status(500).json({ error: 'Internal server error' });
  }
});
`).join('\n')}

module.exports = router;
`;
}

function generateReadme(config: AppConfig): string {
  return `# ${config.name}

${config.description || ''}

## Generated by AppForge

### Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Copy \`.env.example\` to \`.env\` and fill in your values

3. Run the app:
   \`\`\`bash
   npm run dev
   \`\`\`

### Pages
${config.ui?.pages?.map(p => `- **${p.name}** (\`${p.path}\`)`).join('\n') || 'No pages defined'}

### API Endpoints
${config.api?.endpoints?.map(e => `- \`${e.method} ${e.path}\` — ${e.name}`).join('\n') || 'No endpoints defined'}

### Database Tables
${config.database?.tables?.map(t => `- \`${t.name}\``).join('\n') || 'No tables defined'}
`;
}

// ─── Export to GitHub ─────────────────────────────────────────────────────────
router.post('/:appId/export/github', authMiddleware, async (req: Request, res: Response): Promise<void> => {
  try {
    const appResult = await query(
      'SELECT id, name, config FROM app_configs WHERE id = $1 AND user_id = $2',
      [req.params.appId, req.user!.userId]
    );

    if (appResult.rows.length === 0) {
      res.status(404).json({ error: 'App not found' });
      return;
    }

    const appRow = appResult.rows[0];
    const config: AppConfig = appRow.config;
    const githubToken = process.env.GITHUB_TOKEN;

    if (!githubToken) {
      res.status(503).json({ error: 'GitHub token not configured. Set GITHUB_TOKEN in .env' });
      return;
    }

    const repoName = `appforge-${config.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')}-${Date.now()}`;

    // Create GitHub repository
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `token ${githubToken}`,
        'Content-Type': 'application/json',
        'User-Agent': 'AppForge',
      },
      body: JSON.stringify({
        name: repoName,
        description: config.description || `Generated by AppForge — ${config.name}`,
        private: false,
        auto_init: true,
      }),
    });

    if (!createRepoRes.ok) {
      const err = await createRepoRes.json() as { message: string };
      res.status(400).json({ error: `GitHub repo creation failed: ${err.message}` });
      return;
    }

    const repo = await createRepoRes.json() as { full_name: string; html_url: string };

    // Wait for init
    await new Promise(r => setTimeout(r, 2000));

    const filesToPush = [
      { path: 'README.md', content: generateReadme(config) },
      { path: 'src/App.jsx', content: generateReactComponent(config) },
      { path: 'server/routes.js', content: generateExpressRoutes(config) },
      { path: 'appforge.config.json', content: JSON.stringify(config, null, 2) },
      { path: '.env.example', content: '# Add your environment variables here\nPORT=3000\n' },
    ];

    // Push files
    for (const file of filesToPush) {
      await fetch(`https://api.github.com/repos/${repo.full_name}/contents/${file.path}`, {
        method: 'PUT',
        headers: {
          Authorization: `token ${githubToken}`,
          'Content-Type': 'application/json',
          'User-Agent': 'AppForge',
        },
        body: JSON.stringify({
          message: `Add ${file.path}`,
          content: Buffer.from(file.content).toString('base64'),
        }),
      });
    }

    // Save repo URL
    await query(
      'UPDATE app_configs SET github_repo = $1 WHERE id = $2',
      [repo.html_url, req.params.appId]
    );

    res.json({
      success: true,
      repoUrl: repo.html_url,
      repoName: repo.full_name,
    });
  } catch (err) {
    console.error('GitHub export error:', err);
    res.status(500).json({ error: 'GitHub export failed' });
  }
});

// ─── Download as ZIP structure (JSON) ────────────────────────────────────────
router.get('/:appId/export/structure', authMiddleware, async (req: Request, res: Response): Promise<void> => {
  try {
    const appResult = await query(
      'SELECT config FROM app_configs WHERE id = $1 AND user_id = $2',
      [req.params.appId, req.user!.userId]
    );

    if (appResult.rows.length === 0) {
      res.status(404).json({ error: 'App not found' });
      return;
    }

    const config: AppConfig = appResult.rows[0].config;

    res.json({
      files: [
        { path: 'README.md', content: generateReadme(config), language: 'markdown' },
        { path: 'src/App.jsx', content: generateReactComponent(config), language: 'jsx' },
        { path: 'server/routes.js', content: generateExpressRoutes(config), language: 'javascript' },
        { path: 'appforge.config.json', content: JSON.stringify(config, null, 2), language: 'json' },
      ],
    });
  } catch (err) {
    res.status(500).json({ error: 'Failed to generate structure' });
  }
});

export default router;
